require(dplyr)
require(lubridate)
power<-read.table("household_power_consumption.txt",header=T,sep=";",colClasses = c(NA,NA,"numeric","numeric","numeric","numeric","numeric","numeric","numeric"),na.strings="?")
power$Date<-dmy(power$Date)
power$Time<-hms(power$Time)
pn<-filter(power, year(Date)==2007 & month(Date)==2 &(day(Date)==1 |day(Date)==2))
pn_m<-tbl_df(mutate(pn,dt=paste(Date,Time)))
pn_m$dt<-ymd_hms(pn_m$dt)
png("plot3.png")
plot(pn_m$dt,pn_m$Sub_metering_1,type="l",ylab="Energy Sub Metering",xlab="")
lines(pn_m$dt,pn_m$Sub_metering_2,col="red")
lines(pn_m$dt,pn_m$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub Metering 1","Sub Metering 3","Sub Metering 3"),col=c("black","red","blue"),lty=1)
dev.off()